GluuFederation/oxTrust

server/src/main/java/org/gluu/oxtrust/model/OxAuthClient.java
server/src/main/webapp/WEB-INF/incl/client/clientForm.xhtml

oxTrust : we need ability to set "logout_uri" and "logout_session_required" for client #194

Registration metadata

---

static/src/main/resources/META-INF/resources/schema/oxauth-config.xml.json

Client side method to load private key from JWKS

Client side jwks

---

server/src/main/webapp/WEB-INF/incl/person/personForm.xhtml
static/src/main/resources/META-INF/resources/theme/dist/css/custom.css

Long grant value causes interface to 'break'

oxTrust #282

---

server/src/main/java/org/gluu/oxtrust/ldap/service/ClientService.java
server/src/main/webapp/WEB-INF/incl/client/clientForm.xhtml
static/src/main/resources/META-INF/resources/schema/oxauth-config.xml.json

"Update/Add client" page allows to set id_token's signing algorithm to none, resulting in unsigned id_token

oxTrust #271

---

static/src/main/resources/META-INF/resources/schema/oxauth-config.xml.json

WhiteList / Blacklist redirect_uri's

oxAuth #301

---

static/src/main/resources/META-INF/resources/schema/oxauth-config.xml.json

id_token should not contain user claims unless response_type=id_token

oxAuth #340

---

server/src/main/java/org/gluu/oxtrust/action/UpdateTrustRelationshipAction.java
server/src/main/java/org/gluu/oxtrust/ldap/service/FilterService.java
server/src/main/java/org/gluu/oxtrust/ldap/service/ProfileConfigurationService.java

Also fixing NPE if templates for filters and profilesare not there

Filtering out userPassword from release attributes

---

static/src/main/resources/META-INF/resources/schema/oxauth-config.xml.json

oxAuth #458
Improve CORS configuration

Improve CORS configuration

---

server/src/main/webapp/organization/updateOrganization.xhtml

remove update password - #226

---

server/src/main/webapp/WEB-INF/incl/organization/organizationForm.xhtml

we are not using this dialog except for this button hence removed

remove change password dialog

---

server/src/main/java/org/gluu/oxtrust/action/CustomAttributeAction.java
server/src/main/java/org/gluu/oxtrust/model/GluuCustomAttribute.java
server/src/main/webapp/WEB-INF/incl/person/personForm.xhtml

Added multivalue attributes for person

Add multivalue in person form #371

---

static/src/main/resources/META-INF/resources/schema/oxauth-config.xml.json

Remove validate_token_endpoint

oxAuth #510

---

configuration/template/shibboleth3/idp/metadata-providers.xml.vm
configuration/template/shibboleth3/idp/relying-party.xml.vm
configuration/template/shibboleth3/idp/schema/xenc-schema.xsd
configuration/template/shibboleth3/idp/schema/xmldsig-core-schema.xsd
server/src/main/java/org/gluu/oxtrust/action/UpdateCASAction.java
server/src/main/java/org/gluu/oxtrust/action/UpdateTrustRelationshipAction.java
server/src/main/java/org/gluu/oxtrust/ldap/service/MetadataValidationTimer.java
server/src/main/java/org/gluu/oxtrust/ldap/service/Shibboleth3ConfService.java
server/src/main/java/org/gluu/oxtrust/ldap/service/TrustService.java

Saml tr generation_changes

---

configuration/template/shibboleth3/idp/metadata-providers.xml.vm
configuration/template/shibboleth3/idp/relying-party.xml.vm
configuration/template/shibboleth3/idp/schema/xenc-schema.xsd
configuration/template/shibboleth3/idp/schema/xmldsig-core-schema.xsd
server/src/main/java/org/gluu/oxtrust/action/UpdateCASAction.java
server/src/main/java/org/gluu/oxtrust/action/UpdateTrustRelationshipAction.java
server/src/main/java/org/gluu/oxtrust/ldap/service/MetadataValidationTimer.java
server/src/main/java/org/gluu/oxtrust/ldap/service/Shibboleth3ConfService.java
server/src/main/java/org/gluu/oxtrust/ldap/service/TrustService.java

Saml tr generation - changes

---

server/src/main/java/org/gluu/oxtrust/service/PermissionService.java
server/src/main/java/org/gluu/oxtrust/util/jsf/EqualsValidator.java
server/src/main/webapp/WEB-INF/incl/federation/joinFederationForm.xhtml
server/src/main/webapp/WEB-INF/incl/layout/edit.xhtml
server/src/main/webapp/WEB-INF/incl/layout/menu.xhtml
server/src/main/webapp/WEB-INF/incl/layout/newEdit.xhtml
server/src/main/webapp/WEB-INF/incl/layout/simpleDoublePropertiesList.xhtml
server/src/main/webapp/WEB-INF/incl/organization/cacheRefreshForm.xhtml
server/src/main/webapp/WEB-INF/incl/organization/organizationForm.xhtml
server/src/main/webapp/WEB-INF/incl/organization/scimForm.xhtml
server/src/main/webapp/WEB-INF/incl/profile/person/configureListingOptions.xhtml
server/src/main/webapp/WEB-INF/incl/trustmanager/entityIdSelector.xhtml
server/src/main/webapp/WEB-INF/incl/trustmanager/federationDeconstruction.xhtml
server/src/main/webapp/WEB-INF/incl/trustmanager/viewPOPMessage.xhtml
server/src/main/webapp/logviewer/configureLogViewer.xhtml
server/src/main/webapp/logviewer/viewLogFile.xhtml
server/src/main/webapp/profile/person/viewProfile.xhtml
server/src/main/webapp/register.xhtml
server/src/main/webapp/resources/ox/simpleCustomPropertiesList.xhtml
server/src/main/webapp/resources/ox/simplePropertiesList.xhtml
server/src/main/webapp/uma/inventory.xhtml
server/src/main/webapp/uma/resource.xhtml
server/src/main/webapp/uma/resource/modifyResourceSet.xhtml
server/src/main/webapp/uma/scope.xhtml
server/src/main/webapp/uma/scope/modifyScopeDescription.xhtml
server/src/main/webapp/whitePage/viewWhitePages.xhtml

Replaced some seam tags with jsf analog

---

server/src/main/java/org/gluu/oxtrust/action/ConfigureLogViewerAction.java
server/src/main/java/org/gluu/oxtrust/ldap/service/AppInitializer.java
server/src/main/java/org/gluu/oxtrust/model/GluuAppliance.java
server/src/main/java/org/gluu/oxtrust/service/logger/LoggerService.java
server/src/main/webapp/logviewer/configureLogViewer.xhtml

Added possibility to set external logger configuration

---

server/src/main/java/org/gluu/oxtrust/service/logger/LoggerService.java

- added support for logging level config

---

server/src/main/java/org/gluu/oxtrust/ldap/service/MetadataValidationTimer.java
server/src/main/java/org/gluu/oxtrust/ldap/service/Shibboleth3ConfService.java

Reverts GluuFederation/oxTrust#563
Some parts of my code has been deleted. I've restored initial state and fixed "compile errrors".

Revert "resolved compile errrors."

---

server/pom.xml

- added new profile for native2ascii

---

static/src/main/resources/META-INF/resources/schema/oxauth-config.xml.json

oxAuth #577

---

static/src/main/resources/META-INF/resources/schema/oxauth-config.xml.json

Remove long-lived access token exchange

oxAuth #524

---

server/src/main/java/org/gluu/oxtrust/action/AttributeResolverAction.java
server/src/main/java/org/gluu/oxtrust/config/ConfigurationFactory.java
server/src/main/resources/oxtrust.properties
server/src/main/webapp/WEB-INF/incl/layout/leftmenu.xhtml
server/src/main/webapp/resolveattribute/resolveCustomAttribute.page.xml
server/src/main/webapp/resolveattribute/resolveCustomAttribute.xhtml

oxTrust#562

---

server/src/main/java/org/gluu/oxtrust/action/AttributeResolverAction.java
server/src/main/resources/oxtrust.properties
server/src/main/webapp/WEB-INF/incl/layout/leftmenu.xhtml
server/src/main/webapp/resolveattribute/resolveCustomAttribute.page.xml
server/src/main/webapp/resolveattribute/resolveCustomAttribute.xhtml

add custom name attribute

---

server/src/main/webapp/WEB-INF/incl/layout/leftmenu.xhtml

Resolve broken import file functionality

---

server/src/main/java/org/gluu/oxtrust/ldap/service/ImageRepository.java
server/src/main/java/org/gluu/oxtrust/servlet/FaviconImageServlet.java
server/src/main/java/org/gluu/oxtrust/servlet/LogoImageServlet.java
server/src/main/webapp/WEB-INF/incl/layout/leftmenu.xhtml

change content type and servlet mapping path

---

server/src/main/java/org/gluu/oxtrust/action/ConfigureLogViewerAction.java

change message display on error and info

---

static/src/main/resources/META-INF/resources/schema/oxauth-config.xml.json

Add real session state support

oxAuth #592

---

server/src/main/java/org/gluu/oxtrust/service/PermissionService.java

Added check to allow user role type to access profile page.

oxTrust#658

---

server/src/main/resources/oxtrust_en.properties
server/src/main/webapp/WEB-INF/incl/attribute/attributeForm.xhtml
server/src/main/webapp/person/personInventory.xhtml
server/src/main/webapp/resources/ox/decorate.xhtml

Bad error message on search with no values:- Added requiredMessage.

oxTrust#652

---

server/src/main/webapp/resources/ox/selectMemberDialog.xhtml

oxTrust#669

---

server/src/main/webapp/WEB-INF/incl/organization/organizationForm.xhtml

called logo servlet with preview.

oxTrust#664

---

server/src/main/java/org/gluu/oxtrust/action/AttributeResolverAction.java

Added message to notify nameid attribute creation

oxTrust#665

---

server/src/main/webapp/organization/manageRegistration.xhtml

Modified code which was causing error.

oxTrust#657

---

server/src/main/webapp/WEB-INF/incl/layout/leftmenu.xhtml
server/src/main/webapp/configuration/updateConfiguration.xhtml

Changed breadcrumb link in updateConfiguration.xhtml and modified javascript code to highlight attribute link.

OxTrust#672

---

server/src/main/webapp/uma/scope/modifyScopeDescription.xhtml

oxTrust#684

---

server/src/main/java/org/gluu/oxtrust/action/AttributeResolverAction.java

provided path for attribute-resolver.xml.vm for ce installed enviornment

oxTrust#674

---

server/src/main/webapp/WEB-INF/incl/layout/topmenu.xhtml

showing logo as updated in organization configuration.

oxTrust#688

---

server/src/main/java/org/gluu/oxtrust/ldap/service/GroupService.java
server/src/main/java/org/gluu/oxtrust/service/antlr/scimFilter/util/ListResponseGroupSerializer.java
server/src/main/java/org/gluu/oxtrust/service/antlr/scimFilter/util/ListResponseUserSerializer.java
server/src/main/java/org/gluu/oxtrust/service/scim2/jackson/custom/ExtensionDeserializer.java
server/src/main/java/org/gluu/oxtrust/service/scim2/jackson/custom/UserDeserializer.java
server/src/main/java/org/gluu/oxtrust/service/scim2/jackson/custom/UserSerializer.java
server/src/main/java/org/gluu/oxtrust/service/scim2/jackson/provider/CustomJacksonProviderScim2.java
server/src/main/java/org/gluu/oxtrust/service/scim2/schema/strategy/FidoDeviceCoreLoadingStrategy.java
server/src/main/java/org/gluu/oxtrust/service/scim2/schema/strategy/GroupCoreLoadingStrategy.java
server/src/main/java/org/gluu/oxtrust/service/scim2/schema/strategy/UserCoreLoadingStrategy.java
server/src/main/java/org/gluu/oxtrust/service/scim2/schema/strategy/UserExtensionLoadingStrategy.java
server/src/main/java/org/gluu/oxtrust/service/scim2/schema/strategy/serializers/SchemaTypeAbstractSerializer.java
server/src/main/java/org/gluu/oxtrust/service/scim2/schema/strategy/serializers/SchemaTypeFidoDeviceSerializer.java
server/src/main/java/org/gluu/oxtrust/service/scim2/schema/strategy/serializers/SchemaTypeGroupSerializer.java
server/src/main/java/org/gluu/oxtrust/service/scim2/schema/strategy/serializers/SchemaTypeUserSerializer.java
server/src/main/java/org/gluu/oxtrust/util/CopyUtils2.java
server/src/main/java/org/gluu/oxtrust/util/DateUtil.java

This branch has changes to scim-server code.  Mostly weld injection fixes and serialization adjustments
This version passes all SCIM-Client tests in local dev environment

SCIM fixes 3.1.0

---

server/src/main/webapp/WEB-INF/incl/trustmanager/trustRelationshipForm.xhtml

hide url input field when Federation is selected as metadata type.

oxTrust#679

---

server/src/main/java/org/gluu/oxtrust/action/RegisterPersonAction.java
server/src/main/webapp/WEB-INF/incl/person/personForm.xhtml
server/src/main/webapp/register.xhtml

replace rich:validator with f:ajax and added log message for username already exists.

oxTrust#698

---

server/src/main/webapp/WEB-INF/incl/authentication/customAuthenticationForm.xhtml

commented cas enable proxy checkbox

oxTrust#566

---

server/src/main/java/org/gluu/oxtrust/action/AttributeResolverAction.java

Modified AttributeResolverAction to not directly updating attribute-resolver.xml.vm

oxTrust#690

---

server/src/main/webapp/WEB-INF/incl/organization/cacheRefreshForm.xhtml
server/src/main/webapp/resources/ox/ldapConfig.xhtml

oxTrust#159

---

server/src/main/webapp/WEB-INF/incl/person/personForm.xhtml

fixed to work tab key for rich:inplaceInput

oxTrust#654

---

server/src/main/java/org/gluu/oxtrust/model/OxAuthClient.java
server/src/main/resources/oxtrust.properties
server/src/main/resources/oxtrust_en.properties
server/src/main/resources/oxtrust_fr.properties
server/src/main/resources/oxtrust_ru.properties
server/src/main/webapp/WEB-INF/incl/client/clientForm.xhtml

- added disabled field to the client

---

server/src/main/webapp/WEB-INF/incl/person/personForm.xhtml

changed code to show textbox after three clicks.

oxTrust#728

---

static/src/main/resources/META-INF/resources/schema/oxauth-config.xml.json

Invalid "scopes" field in Dynamic Client Registration request and response

oxAuth #700

---

server/src/main/webapp/WEB-INF/incl/trustmanager/trustRelationshipForm.xhtml

certificate' corresponding to in file upload field.

oxTrust/issues/#874 : added the same condition for label 'Update public

---

pom.xml

Downgrade **jsf library** from **2.2.17** to **2.2.16** fix the issue.

Fix files upload issue in 3.1.3 #1007

---

model/src/main/java/org/gluu/oxtrust/model/Device.java
model/src/main/java/org/gluu/oxtrust/model/GluuCustomPerson.java
model/src/main/java/org/gluu/oxtrust/model/MobileDevice.java
model/src/main/java/org/gluu/oxtrust/model/OTPDevice.java
model/src/main/java/org/gluu/oxtrust/model/Phone.java
server/src/main/java/org/gluu/oxtrust/action/UpdatePersonAction.java
server/src/main/webapp/WEB-INF/incl/person/personForm.xhtml

Show Modality for otp, mobile, passport, fido devices.

Ox trust/issues/#815

---

server/src/main/java/org/gluu/oxtrust/action/uma/UpdateResourceAction.java
server/src/main/webapp/WEB-INF/incl/layout/jqueryJsonEditor.xhtml
server/src/main/webapp/uma/resource.xhtml
server/src/main/webapp/uma/resource/modifyResource.xhtml

#808 and #865 : Added add resource button and make some changes for

---

static/src/main/resources/META-INF/resources/schema/oxmemcache-config.json

#1018 : New redis configuration ssl parameters support

#1018 : New redis configuration ssl parameters support

---

pom.xml
server/pom.xml
server/src/main/webapp/WEB-INF/incl/client/clientForm.xhtml
server/src/main/webapp/resources/ox/clientSummary.xhtml

#1040 : Add client config summary popup and also added primefaces lib in oxtrust.

#1040 : Add client config summary popup

---

model/src/main/java/org/gluu/oxtrust/model/registration/ManagementRegReqParam.java
server/profiles/skhan/config-build.properties
server/profiles/skhan/config-oxtrust-test-data.properties
server/profiles/skhan/config-oxtrust-test.properties
server/profiles/skhan/config-oxtrust.properties
server/src/main/java/org/gluu/oxtrust/api/RegistrationManagementService.java
server/src/main/java/org/gluu/oxtrust/api/client/RegistrationManagementRequest.java
server/src/main/java/org/gluu/oxtrust/api/client/RegistrationManagementResponse.java
server/src/test/java/org/gluu/oxtrust/api/registration/management/test/ManagementRegServiceTest.java
server/src/test/java/org/gluu/oxtrust/service/TestResteasyInitializer.java

@yurem  . Completed the API for registration management action. Please review.

Oxtrust api

---

server/src/main/java/org/gluu/oxtrust/action/ManagePersonAuthenticationAction.java
server/src/main/resources/oxtrust.properties
server/src/main/webapp/WEB-INF/incl/authentication/customAuthenticationForm.xhtml

added recaptcha tab on manage autheticate page.

#1072 : added recaptcha tab on manage autheticate page.

---

server/src/main/java/org/gluu/oxtrust/action/UpdateOrganizationAction.java
server/src/main/webapp/WEB-INF/incl/organization/organizationForm.xhtml

@yurem please merge if you agree to my comment https://github.com/GluuFederation/oxTrust/issues/1091#issuecomment-412969821

#1091 remove buildDate and buildNumber from organization oxTrustSettings

---

server/src/main/java/org/gluu/oxtrust/action/ConfigureCacheRefreshAction.java

#1092 fix typo

---

server/src/main/resources/oxtrust.properties
server/src/main/webapp/WEB-INF/incl/client/clientForm.xhtml
server/src/main/webapp/client/updateClient.xhtml
server/src/main/webapp/resources/ox/clientSummary.xhtml

Removed primefaces to fix re-render functionality for other components.

#1040 : removed primefaces

---

server/src/main/java/org/gluu/oxtrust/action/ManagePersonAuthenticationAction.java
server/src/main/webapp/WEB-INF/incl/authentication/customAuthenticationForm.xhtml
server/src/main/webapp/organization/manageRegistration.xhtml

correct the pull request :1230 and change the label for enable\disable captcha checkbox consistent.

#1072 : removed unwanted captcha site and key,changed label

---

server/src/main/java/org/gluu/oxtrust/service/MetricService.java

This causes a dependecy injection exception.
Please merge ASAP

#1342 remove unused dependency

---

configuration/template/shibboleth3/idp/attribute-resolver.xml.vm
configuration/template/shibboleth3/idp/saml-nameid.properties.vm
configuration/template/shibboleth3/idp/saml-nameid.xml.vm
server/src/main/java/org/gluu/oxtrust/action/ManageCustomScriptAction.java
server/src/main/java/org/gluu/oxtrust/ldap/service/Shibboleth3ConfService.java
server/src/main/webapp/WEB-INF/incl/script/customScriptListForm.xhtml
server/src/main/webapp/saml/configureNameId.xhtml

Changes in reference to
Gluu Server SAML NameID enhacement #1651
Map AuthnContextClassRef --> acr in OpenID Connect #15

acr and nameid enhancements

---

server/src/main/java/org/gluu/oxtrust/action/ConfigureNameIdAction.java

nameid update - restart not required (when oxTrust amd idp are on same host)

nameid update - restart not required

---

configuration/template/shibboleth3/idp/saml-nameid.xml.vm
server/src/main/java/org/gluu/oxtrust/action/ConfigureNameIdAction.java

minor fixes, removed unspecified not supported by shibb itself (deprecated)

nameid-fixes-with-4.0

---

configuration/template/shibboleth3/idp/ProfileConfiguration/SAML2SSOProfileConfiguration.xml.vm
configuration/template/shibboleth3/idp/relying-party.xml.vm
model/src/main/java/org/gluu/oxtrust/model/ProfileConfiguration.java
server/src/main/java/org/gluu/oxtrust/action/RelyingPartyAction.java
server/src/main/java/org/gluu/oxtrust/ldap/service/ProfileConfigurationService.java
server/src/main/webapp/WEB-INF/incl/trustmanager/profileConfiguration/saml1sso.xhtml
server/src/main/webapp/WEB-INF/incl/trustmanager/profileConfiguration/saml2sso.xhtml

Fixes default NameID and AuthContextRef Support

Fixes #1722 #1723

---

configuration/src/main/resources/META-INF/shibboleth3/idp/ProfileConfiguration/SAML2SSOProfileConfiguration.xml.vm
model/src/main/java/org/gluu/oxtrust/model/ProfileConfiguration.java
server/src/main/java/org/gluu/oxtrust/action/RelyingPartyAction.java
server/src/main/java/org/gluu/oxtrust/ldap/service/ProfileConfigurationService.java
server/src/main/webapp/WEB-INF/incl/trustmanager/profileConfiguration/saml2sso.xhtml

Name id format precedence backend support

---

model/src/main/java/org/gluu/oxtrust/model/GluuConfiguration.java
server/src/main/java/org/gluu/oxtrust/action/ProductInstallationCheckerAction.java

* Added code to turn on/off Radius menu from Gluu Configuration
* Added code to turn on/off SAML menu from Gluu Configuration

Changes in this commit:

---

server/src/main/java/org/gluu/oxtrust/action/SamlAcrAction.java
server/src/main/java/org/gluu/oxtrust/ldap/service/SamlAcrService.java
server/src/main/java/org/gluu/oxtrust/ldap/service/Shibboleth3ConfService.java
server/src/main/java/org/gluu/oxtrust/ldap/service/ShibbolethInitializer.java
server/src/main/java/org/gluu/oxtrust/ldap/service/ShibbolethService.java

Acr vm template support

---

api-server/src/main/java/org/gluu/oxtrust/api/server/api/impl/GroupWebResource.java
api-server/src/main/java/org/gluu/oxtrust/api/server/api/impl/PeopleWebResource.java
api-server/src/main/java/org/gluu/oxtrust/api/server/api/impl/ScopeWebResource.java
api-server/src/main/java/org/gluu/oxtrust/api/server/api/impl/UmaScopeWebResource.java

* Fixed build issue related to javadoc like comments in code

Pull request from Rolain Djeumen

---

api-server/src/main/java/org/gluu/oxtrust/api/server/api/impl/PeopleWebResource.java

* Fix method being innapropriately annotated.

Fix method being innapropriately annotated.

---

server/src/main/java/org/gluu/oxtrust/ldap/service/ClientService.java
server/src/main/java/org/gluu/oxtrust/ldap/service/IdGenService.java

* Fixes for github issue #1914

Pull request for issue #1914

---

static/src/main/resources/META-INF/resources/schema/oxauth-config.xml.json

oxAuth related issue: GluuFederation/oxAuth#1252

Added flag to toggle default code flow behaviour

---

server/src/main/java/org/gluu/oxtrust/action/UpdateScopeAction.java
server/src/main/resources/oxtrust.properties
server/src/main/resources/oxtrust_en.properties
server/src/main/resources/oxtrust_fr.properties
server/src/main/resources/oxtrust_ru.properties
server/src/main/webapp/WEB-INF/incl/scope/scopeForm.xhtml

Related to this issue: GluuFederation/oxAuth#1370

New scope attribute to publish or not in discovery endpoint

---

server/src/main/java/org/gluu/oxtrust/action/UpdateScopeAction.java
server/src/main/resources/oxtrust.properties
server/src/main/resources/oxtrust_en.properties
server/src/main/resources/oxtrust_fr.properties
server/src/main/resources/oxtrust_ru.properties
server/src/main/webapp/WEB-INF/incl/scope/scopeForm.xhtml
static/src/main/resources/META-INF/resources/schema/oxScopeAttributes.properties.json

Related to issue: https://github.com/GluuFederation/oxAuth/issues/1370

Moved notShowInDiscovery Scope attribute to ScopeAttributes json object.

---

service/src/main/java/org/gluu/oxtrust/service/ConfigurationService.java

Added CIBA interception script type

---

static/src/main/resources/META-INF/resources/schema/oxauth-config.xml.json

Issue: https://github.com/GluuFederation/oxAuth/issues/141

Device authz

---

configuration/src/main/resources/META-INF/shibboleth3/idp/attribute-resolver.xml.vm
configuration/src/main/resources/META-INF/shibboleth3/idp/gluu-attribute-rules.xml.vm
server/src/main/java/org/gluu/oxtrust/service/AppInitializer.java
server/src/main/java/org/gluu/oxtrust/service/ShibbolethInitializer.java
server/src/main/java/org/gluu/oxtrust/service/TranscodingRulesUpdater.java
server/src/main/java/org/gluu/oxtrust/util/CloudEditionUtil.java
service/src/main/java/org/gluu/oxtrust/service/Shibboleth3ConfService.java
service/src/main/java/org/gluu/oxtrust/service/ShibbolethReloadService.java
service/src/main/java/org/gluu/oxtrust/service/cdi/event/TranscodingRulesUpdateEvent.java

Added code to generate Shibboleth 4 style transcoding rules
which are useful in the resolution of issue #74 in oxShibboleth

fix: add shibboleth transcoding rules generation

---

static/src/main/resources/META-INF/resources/schema/oxmemcache-config.json

Issue: https://github.com/GluuFederation/oxCore/issues/215
Related PRs:
- https://github.com/GluuFederation/gluu-core-bom/pull/12
- https://github.com/GluuFederation/oxCore/pull/221

Added params to handle keystores properly

---

static/src/main/resources/META-INF/resources/schema/oxmemcache-config.json

Cherry pick from https://github.com/GluuFederation/oxTrust/pull/2114

Added params to handle keystores properly (#2114)

---

service/src/main/java/org/gluu/oxtrust/model/OxTrustedIdp.java
service/src/main/java/org/gluu/oxtrust/service/TrustedIDPService.java

feat: add new Trust-IDP apis

---

server/src/main/java/org/gluu/oxtrust/action/UpdateOrganizationAction.java

#2128 : contact mail in system configuration

fix(oxtrust): contact mail in system configuration

---

server/src/main/java/org/gluu/oxtrust/action/PasswordValidationAction.java
server/src/main/java/org/gluu/oxtrust/action/UpdatePersonAction.java

If user is going to update his own username or password then user will get logout automatically.

fix: after updating username or password user should log out automatically

---

server/src/main/webapp/WEB-INF/incl/person/userForm.xhtml

fix: #2076 allow more character for email validation

---

server/src/main/java/org/gluu/oxtrust/action/AttributeInventoryAction.java
server/src/main/java/org/gluu/oxtrust/service/LdifService.java

fix: import attribute in mysql db

---

server/src/main/java/org/gluu/oxtrust/action/UpdateScopeAction.java

fix: add dynamic script in openid scopes.

---

server/src/main/webapp/WEB-INF/incl/layout/fullWidthEmpty.xhtml
server/src/main/webapp/passwordResetResult.xhtml

fix: remove blue strip for the message.

---

server/src/main/java/org/gluu/oxtrust/action/JsonConfigurationAction.java
service/src/main/java/org/gluu/oxtrust/util/EasyCASSLProtocolSocketFactory.java

chore: remove caCertsLocation, caCertsPassphrase properties

---

static/src/main/resources/META-INF/resources/schema/oxstore-config.json

https://github.com/GluuFederation/oxCore/issues/223

feat: oxcore issue 223 display DB option on ui

---

server/src/main/java/org/gluu/oxtrust/action/ConfigureNameIdAction.java

More details can be found in oxTrust issue #2167

fix: facilitate multiple same type NameID creation

---

static/src/main/resources/META-INF/resources/schema/oxtrust.properties.json

https://github.com/GluuFederation/scim/issues/54

feat: update json properties

---

server/src/main/webapp/WEB-INF/incl/layout/leftmenu.xhtml
service/src/main/java/org/gluu/oxtrust/service/ScopeService.java

fix: remove uma left navigation and add all scopes in openid scope

---

api-server/src/main/resources/META-INF/openapi.yaml

Swagger 4.4.1

---

service/src/main/java/org/gluu/oxtrust/service/ScopeService.java

fix: added oxid in search criteria for scopes

---

server/src/main/java/org/gluu/oxtrust/action/UpdateScopeAction.java
server/src/main/resources/oxtrust_en.properties
server/src/main/webapp/WEB-INF/incl/scope/scopeForm.xhtml
server/src/main/webapp/scope/scopeInventory.xhtml
service/src/main/java/org/gluu/oxtrust/service/ClientService.java
service/src/main/java/org/gluu/oxtrust/service/ScopeService.java
service/src/main/java/org/gluu/oxtrust/util/OxTrustConstants.java

fix: rearrange and addition of fields for scope feature

---

server/src/main/java/org/gluu/oxtrust/action/CustomAttributeAction.java
server/src/main/java/org/gluu/oxtrust/action/UpdatePersonAction.java

fix: #2237 resolve the removal multivalued attribute

---

server/src/main/java/org/gluu/oxtrust/action/UpdateClientAction.java
server/src/main/webapp/WEB-INF/incl/client/clientForm.xhtml

#2211 
removed the newly added attributes.

fix: added the removed attributes #2211

---

server/src/main/java/org/gluu/oxtrust/LanguageBean.java
server/src/main/webapp/WEB-INF/incl/layout/topmenu.xhtml
static/src/main/resources/META-INF/resources/schema/oxtrust.properties.json

#2226  Added locale configuration in DB.

feat: locale configurable

---

api-server/src/main/java/org/gluu/oxtrust/api/server/api/impl/ApiConfigWebRecource.java
api-server/src/main/java/org/gluu/oxtrust/api/server/api/impl/CaptchaConfigWebResource.java
api-server/src/main/java/org/gluu/oxtrust/api/server/api/impl/ExistingLdapConfigurationValidator.java
api-server/src/main/java/org/gluu/oxtrust/api/server/api/impl/IdpConfigWebResource.java
api-server/src/main/java/org/gluu/oxtrust/api/server/api/impl/MetricConfigWebResource.java
api-server/src/main/java/org/gluu/oxtrust/api/server/api/impl/OxAuthConfigurationWebResource.java
api-server/src/main/java/org/gluu/oxtrust/api/server/api/impl/OxTrustConfigurationWebResource.java
api-server/src/main/java/org/gluu/oxtrust/api/server/api/impl/PassportConfigWebResource.java
api-server/src/main/java/org/gluu/oxtrust/api/server/api/impl/RptConfigWebResource.java
api-server/src/main/java/org/gluu/oxtrust/api/server/api/impl/ScimConfigWebResource.java
api-server/src/main/java/org/gluu/oxtrust/api/server/api/impl/SectorIdentifierWebResource.java
api-server/src/main/java/org/gluu/oxtrust/api/server/api/impl/SystemConfigWebResource.java
api-server/src/main/java/org/gluu/oxtrust/api/server/api/impl/TrustedIDPWebResource.java
api-server/src/main/java/org/gluu/oxtrust/api/server/model/ApiConfig.java
api-server/src/main/java/org/gluu/oxtrust/api/server/model/CaptchaConfig.java
api-server/src/main/java/org/gluu/oxtrust/api/server/model/IdpConfig.java
api-server/src/main/java/org/gluu/oxtrust/api/server/model/MetricConfig.java
api-server/src/main/java/org/gluu/oxtrust/api/server/model/OxTrustBasicConfig.java
api-server/src/main/java/org/gluu/oxtrust/api/server/model/PassportConfig.java
api-server/src/main/java/org/gluu/oxtrust/api/server/model/RemoteIdp.java
api-server/src/main/java/org/gluu/oxtrust/api/server/model/RptConfig.java
api-server/src/main/java/org/gluu/oxtrust/api/server/model/ScimConfig.java
api-server/src/main/java/org/gluu/oxtrust/api/server/model/SingleSignOnServices.java
api-server/src/main/java/org/gluu/oxtrust/api/server/model/SystemConfig.java
api-server/src/main/java/org/gluu/oxtrust/api/server/model/TrustedIDPApi.java
api-server/src/main/java/org/gluu/oxtrust/api/server/util/ApiConstants.java

#2245  added Apis related model classes.

feat: added missing apis in oxtrust's api-server module #2245

---

server/src/main/java/org/gluu/oxtrust/action/SearchTrustedIdpAction.java
server/src/main/java/org/gluu/oxtrust/action/UpdateTrustedIdpAction.java
server/src/main/java/org/gluu/oxtrust/model/SingleSignOnServices.java
server/src/main/resources/META-INF/navigation/addTrustedIdp.navigation.xml
server/src/main/resources/META-INF/navigation/trustedIdpInventory.navigation.xml
server/src/main/resources/META-INF/navigation/updateTrustedIdp.navigation.xml
server/src/main/resources/oxtrust_en.properties
server/src/main/webapp/WEB-INF/incl/layout/leftmenu.xhtml
server/src/main/webapp/WEB-INF/incl/trustedidp/singleSignOnServiceForm.xhtml
server/src/main/webapp/WEB-INF/incl/trustedidp/trustedIdpForm.xhtml
server/src/main/webapp/trustedidp/addTrustedIdp.xhtml
server/src/main/webapp/trustedidp/trustedIdpInventory.xhtml
server/src/main/webapp/trustedidp/updateTrustedIdp.xhtml
service/src/main/java/org/gluu/oxtrust/service/TrustedIDPService.java
service/src/main/java/org/gluu/oxtrust/util/OxTrustConstants.java

feat: Inbound GluuSAML UI #2246

---

service/src/main/java/org/gluu/oxtrust/service/Shibboleth3ConfService.java

https://github.com/GluuFederation/oxCore/issues/244

feat : update multiple oxmodule

---

configuration/src/main/resources/META-INF/shibboleth3/idp/mdq-metadata.xml.vm
model/src/main/java/org/gluu/oxtrust/model/GluuMetadataSourceType.java
server/src/main/java/org/gluu/oxtrust/action/UpdateTrustRelationshipAction.java
server/src/main/webapp/WEB-INF/incl/trustmanager/trustForm.xhtml
service/src/main/java/org/gluu/oxtrust/service/Shibboleth3ConfService.java

https://github.com/GluuFederation/oxTrust/issues/1704

feat(oxtrust) : Support SAML MDQ

---

server/src/main/java/org/gluu/oxtrust/service/AppInitializer.java
server/src/main/java/org/gluu/oxtrust/service/CleanUpFilesDaily.java

feat(oxtrust-server) : Remove files in var/gluu/identity/removed #2225

---

server/src/main/java/org/gluu/oxtrust/ldap/cache/service/CacheRefreshTimer.java
server/src/main/java/org/gluu/oxtrust/model/GluuUserPairwiseIdentifier.java
service/src/main/java/org/gluu/oxtrust/util/OxTrustConstants.java

#2209  cache refresh remove person subentries for all orms

fix: cache refresh should remove persons sub entries on removal #2209

---

api-server/src/main/java/org/gluu/oxtrust/api/server/api/impl/TrustRelationshipWebService.java
model/src/main/java/org/gluu/oxtrust/model/GluuMetadataSourceType.java
model/src/main/java/org/gluu/oxtrust/model/GluuSAMLTrustRelationship.java

fix(oxtrust-api): added metadata validator on saml services #2264

---

server/src/main/java/org/gluu/oxtrust/action/TrustRelationshipInventoryAction.java

feat(oxtrust): display more than 100+ records #2262

---

service/src/main/java/org/gluu/oxtrust/auth/OxTrustApiService.java
static/src/main/resources/META-INF/resources/schema/oxtrust.properties.json

feat : added oauth protection on oxtrust apis

---

server/src/main/webapp/WEB-INF/incl/layout/topmenu.xhtml

fix(oxtrust-server): remove Locale dropdown from to top menu

---

server/src/main/java/org/gluu/oxtrust/action/UpdateClientAction.java

feat(oxtrust-server): enable support for deep link on client redirectUri

---

api-server/src/main/java/org/gluu/oxtrust/api/server/api/impl/TrustedIDPWebResource.java

fix(oxtrust-server-api): add response message in delete operation #2261

---

service/src/main/java/org/gluu/oxtrust/service/JsonConfigurationService.java

feat(oxtrust-server): added audit log files for config changes #2266

---

model/src/main/java/org/gluu/oxtrust/model/AuditConfigLogDetails.java
service/src/main/java/org/gluu/oxtrust/service/JsonConfigurationService.java

feat(oxtrust-server): added null checks in implementations

---

server/src/main/java/org/gluu/oxtrust/action/UpdateClientAction.java
server/src/main/webapp/client/addClient.xhtml
server/src/main/webapp/client/updateClient.xhtml

feat: added search box to filter scopes

---

service/src/main/java/org/gluu/oxtrust/service/PersonService.java

fix: move first name and last name nearby

---

server/src/main/java/org/gluu/oxtrust/action/UpdatePersonAction.java

fix(oxtrust-server): password regex validator null pointer exception

---

server/src/main/webapp/WEB-INF/incl/client/clientForm.xhtml

fix(oxtrust-server): save oxAuthDefaultAcrValues name instead of inum

---

server/src/main/java/org/gluu/oxtrust/action/UpdateClientAction.java
server/src/main/java/org/gluu/oxtrust/model/OxAuthClient.java
server/src/main/webapp/WEB-INF/incl/client/clientForm.xhtml
server/src/main/webapp/client/addClient.xhtml
server/src/main/webapp/client/updateClient.xhtml

fix(oxtrust-server): add multiple front and back logout uri

---

pom.xml

fix(oxtrust-server): #2334 updated the dependency versions

---

server/src/main/java/org/gluu/oxtrust/util/PasswordValidator.java
server/src/main/webapp/resetPassword.xhtml

fix(oxtrusr-server): password reset oops page

---

server/src/main/java/org/gluu/oxtrust/action/RegisterPersonAction.java
server/src/main/webapp/register.xhtml

fix(oxtrust-server): password validation on self registration page

---

server/src/main/java/org/gluu/oxtrust/action/UpdateClientAction.java

fix(oxtrust-server): #2303 update in localhost and http rule

---

server/src/main/java/org/gluu/oxtrust/action/PasswordResetAction.java

fix(oxtrust-server): avoid success page when passwords mismatching

---

server/src/main/java/org/gluu/oxtrust/service/MetadataValidationTimer.java

fix(oxtrust-server):  validate TR metadata

---

server/src/main/java/org/gluu/oxtrust/action/UpdateClientAction.java

fix(oxtrust-server): handle for invalid sector uri #2354

---

server/src/main/webapp/WEB-INF/incl/person/userForm.xhtml

fix(oxtrust-server): update mail validation #2357

---

pom.xml
server/pom.xml
server/src/main/java/org/gluu/oxtrust/action/ConfigurationStatusAction.java
server/src/main/webapp/status/applicationStatus.xhtml

feat(oxtrust-server): added mau stats on ui #2346

---

server/src/main/java/org/gluu/oxtrust/action/SearchClientAction.java

fix(oxtrust-server): display name sorting null issue #2348

---

server/src/main/java/org/gluu/oxtrust/action/UpdateClientAction.java
server/src/main/webapp/client/addClient.xhtml
server/src/main/webapp/client/updateClient.xhtml

Add Search Field for Scopes Selection in OpenID Client

---

server/src/main/webapp/WEB-INF/incl/layout/leftmenu.xhtml

refactor(oxtrust-server): #2372 remove trusted idp form

---

server/src/main/java/org/gluu/oxtrust/action/UpdatePersonAction.java

#2378 updated functionality to make sync oxTrustActive with gluuStatus.

feat(oxtrust=server): #2378 sync gluuStatus with oxTrustActive attribute

---

api-server/src/main/resources/META-INF/openapi.json
api-server/src/main/resources/META-INF/openapi.yaml

feat(oxtrust-api-server): #2380 add swagger doc

---

api-server/src/main/resources/META-INF/openapi.json
api-server/src/main/resources/META-INF/openapi.yaml

4.5.0 issues 2380

---

server/src/main/java/org/gluu/oxtrust/action/PassportProvidersAction.java

feat(passport): update passport-saml to @node-saml/passport-saml

---

api-server/src/main/java/org/gluu/oxtrust/api/server/api/impl/BaseWebResource.java
api-server/src/main/resources/META-INF/openapi.json
api-server/src/main/resources/META-INF/openapi.yaml

#2380 updated doc details for 4.5.1

feat(oxtrust-api-server): #2380 updated doc details

---

api-server/src/main/java/org/gluu/oxtrust/api/server/api/impl/BaseWebResource.java
api-server/src/main/resources/META-INF/openapi.json
api-server/src/main/resources/META-INF/openapi.yaml

#2380 updated doc details for 4.5.1.sp1

fix(oxtrust-api-server): #2380 updated doc details

---

server/src/main/java/org/gluu/oxtrust/action/RegisterPersonAction.java

fix(oxtrust-server):  message change on registration success page

---

server/src/main/webapp/WEB-INF/incl/client/clientForm.xhtml
server/src/main/webapp/WEB-INF/incl/organization/organizationForm.xhtml
server/src/main/webapp/client/clientInventory.xhtml
server/src/main/webapp/scope/scopeInventory.xhtml

upgraded the style and js libs.
https://github.com/GluuFederation/gluu-core-bom/issues/38

feat(gluu-core-bom): fix design for bootstrap 5

---

server/src/main/java/org/gluu/oxtrust/action/RegisterPersonAction.java

fix(oxtrust): password mismatch error on registration page

---

server/src/main/java/org/gluu/oxtrust/action/UpdateClientAction.java
server/src/main/webapp/WEB-INF/incl/client/clientForm.xhtml

fix(oxtrust): select different introspection script in OpenID Client

---

static/src/main/resources/META-INF/resources/schema/fido2-config.json

feat(oxTrust): add missing option to fido2 schema file

---

static/src/main/resources/META-INF/resources/schema/oxauth-config.xml.json

feat(oxtrust): add allowwildcardredirecturi on oxauth config ui #2436
